apiVersion: v2
name: routehub-client-hub
description: A Helm chart for RouteHub Client deployment
home: https://github.com/RouteHub-Link/RouteHub.HELM
icon: https://avatars.githubusercontent.com/u/153122518?s=240
keywords:
  - routehub
  - client
  - mqtt
  - rest
sources:
    - https://github.com/RouteHub-Link/RouteHub.HELM/tree/main/client
    - https://github.com/RouteHub-Link/RouteHub.Client.Hub
maintainers:
  - name: runaho
    email: guneskorkmaz@outlook.com.tr

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"
