apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "routehub-client.labels" . | nindent 4 }}
    component: redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "routehub-client.labels" . | nindent 6 }}
      component: redis
  template:
    metadata:
      labels:
        {{- include "routehub-client.labels" . | nindent 8 }}
        component: redis
    spec:
      containers:
        - name: {{ .Chart.Name }}-redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: 6379
