apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mqtt
  labels:
    {{- include "routehub-client.labels" . | nindent 4 }}
    component: mqtt
spec:
  type: {{ .Values.routehubClientMqtt.service.type }}
  ports:
    - port: {{ .Values.routehubClientMqtt.service.port }}
      targetPort: 1883
  selector:
    {{- include "routehub-client.labels" . | nindent 4 }}
    component: mqtt
