apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-timescale
  labels:
    {{- include "routehub-client.labels" . | nindent 4 }}
    component: timescale
spec:
  type: {{ .Values.timescale.service.type }}
  ports:
    - port: {{ .Values.timescale.service.port }}
      targetPort: 5432
  selector:
    {{- include "routehub-client.labels" . | nindent 4 }}
    component: timescale
