apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  labels:
    {{- include "routehub-server.labels" . | nindent 4 }}
    component: server
spec:
  type: {{ .Values.routehubServer.service.type }}
  ports:
    - port: {{ .Values.routehubServer.service.port }}
      targetPort: 8080
  selector:
    {{- include "routehub-server.labels" . | nindent 4 }}
    component: server
